name: flashcards
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0

  #signIn
  google_sign_in: ^6.0.2
  google_sign_in_web: ^0.12.0
  sign_in_with_apple: ^4.3.0

  #packages
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  go_router: ^13.0.1
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.9
  crypto: ^3.0.3
  async: ^2.8.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_colorpicker: ^1.0.3
  dialog_alert: ^0.0.3
  share_plus: ^7.2.1
  flutter_keyboard_visibility: ^6.0.0
  file_picker: ^6.2.0
  open_file_plus: ^3.4.1
  path_provider: ^2.1.2
  excel: ^4.0.2
  shared_preferences: ^2.2.2
  qr_code_scanner: ^1.0.1

  flutter_quill: ^9.2.12
  flutter_html: any
  adaptive_action_sheet: ^2.0.3
  flutter_markdown: ^0.6.20




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  generate: true
  uses-material-design: true


  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600


