// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATxURl449Vcqq2fNHSHE8bBJp4mfnp_2k',
    appId: '1:393510478049:web:a3961386adacbb971b57a0',
    messagingSenderId: '393510478049',
    projectId: 'flashcards-5984c',
    authDomain: 'flashcards-5984c.firebaseapp.com',
    storageBucket: 'flashcards-5984c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsGx7f0VBBKXGnZfnX4oryeWFfoCt0Is',
    appId: '1:393510478049:android:020ecddb810fc5e01b57a0',
    messagingSenderId: '393510478049',
    projectId: 'flashcards-5984c',
    storageBucket: 'flashcards-5984c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtbW3idPjLre5rUI83Wji3y9g3vlpfpPM',
    appId: '1:393510478049:ios:6d25417cdda020621b57a0',
    messagingSenderId: '393510478049',
    projectId: 'flashcards-5984c',
    storageBucket: 'flashcards-5984c.appspot.com',
    androidClientId: '393510478049-ketfkj1s0apvatgbm8q53tam1i4kvkmp.apps.googleusercontent.com',
    iosClientId: '393510478049-0a6ajnahhrp200orlg169r85dsfefdj2.apps.googleusercontent.com',
    iosBundleId: 'com.pandascode.flashcards',
  );
}
